### ISSUE TITLE
RSS validation might fail

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#633] opened 2020-07-22 16:10 UTC
In investigating the recent rss issue I came across something that could be an issue for future feeds.

Recently we fixed an issue with RSS feeds where if the url included any query parameters, those were not being added when the feed was requested.

What we missed, however, was the validation of the feed when the form is submitted.  

To see if the feed is valid, it requests the url, and makes sure XML is returned. Except we didn't add the query parameter here.  The validation is being done on the url without the query parameters.

If the site returns valid xml WITHOUT the query parameters, the validation will pass. If the site returns something else, the validation will fail, even though the feed would have worked fine without the validation.

**Comment by AlanBCole** [comment] 2020-08-17 17:02
@kevincrafts I used a url with a query parameter in the form found at /block/add/rss. When the function `_cu_rss_block_form_validate()` is called the the value/url found in `$form_state['values']['field_rss_bean_url'][LANGUAGE_NONE][0]['url']` includes the query parameter here. I will try some more urls and let you know if they all act the same.

**Comment by AlanBCole** [comment] 2020-12-02 21:05
@jwfuller It has been a while since I looked at this. Is this issue also related to `drupal_http_request()` only supporting HTTP 1.1?

**Comment by jwfuller** [comment] 2020-12-07 16:01
@AlanBCole I don't think so, but I am not 100% sure.

**Comment by AlanBCole** [comment] 2020-12-16 03:02
@kevincrafts I am looking at this again after a while. I have this situation:

- I created a rss block 
- put its url as `https://rss.nytimes.com/services/xml/rss/nyt/Music.xml?music=yes&rss=true`
- I put a break point up at https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_rss_block/cu_rss_block.module#L44 (this function is called to validate the rss feed upon form submission)
- And followed the `drupal_http_request()` code to https://github.com/CuBoulder/d7core/blob/main/includes/common.inc#L934
- At that line the query parameters are appended to the request url.

This seems to show that the validation function/step does include the query parameters. Or have I misunderstood what you described above in this issue's description (very possible!)?

**Comment by AlanBCole** [comment] 2020-12-17 18:41
Closing this issue. Validation is performed on the full url (with query parameters) typed into the form, so nothing needs to be changed. The confusion was caused by the fact that the url and query parameters are separated after validation as they are saved into the DB. We thought that this might have happened before validation and that validation would then not have included the query parameters.

**Closed by AlanBCole** 2020-12-17 18:41 UTC
Labels: bug, support-impact
