### ISSUE TITLE
Integration with Jobs

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#784] opened 2020-12-16 18:01 UTC
Client has requested integration with Jobs site, they would like to embed the application forms on their site.
https://secure.helpscout.net/conversation/1370819266/5308?folderId=1414566

"I'm wondering if there is a way to take jobs we post here: https://www.colorado.edu/jobs/
And make them auto fill onto our website? Like the campus events, newsletter archive or news archive.

**Comment by jwfuller** [comment] 2021-01-05 20:14
Duplicate of https://github.com/CuBoulder/express_mono/issues/65

**Closed by jwfuller** 2021-01-05 20:14 UTC
