### ISSUE TITLE
Square image photos not set square in content grid teaser display

### ISSUE THREAD

**Issue by johnquest** [CuBoulder/express_mono#302] opened 2019-09-25 15:52 UTC
![feature-style-content-grid](https://user-images.githubusercontent.com/13682205/65617424-f2429f00-df79-11e9-9b03-5b18c031e6d9.png)

**Comment by jwfuller** [comment] 2019-09-30 16:12
Duplicate of #305

**Closed by jwfuller** 2019-09-30 16:12 UTC
